<?php
require_once __DIR__ . '/includes/auth.php';
requireLogin();
$pdo = db(); $uid = userId(); $pageTitle = 'Dashboard'; $activePage = 'dashboard.php';
[$monthStart, $monthEnd] = monthBounds();
$totalIncome = transactionSum($pdo, $uid, 'income');
$totalExpense = transactionSum($pdo, $uid, 'expense');
$incomeMonth = transactionSum($pdo, $uid, 'income', $monthStart, $monthEnd);
$expenseMonth = transactionSum($pdo, $uid, 'expense', $monthStart, $monthEnd);
$balance = $totalIncome - $totalExpense;
$monthBalance = $incomeMonth - $expenseMonth;
$savingsTotal = (float) $pdo->query("SELECT COALESCE(SUM(current_amount),0) FROM savings WHERE user_id = {$uid}")->fetchColumn();
$debtTotal = (float) $pdo->query("SELECT COALESCE(SUM(GREATEST(total_amount-paid_amount,0)),0) FROM debts WHERE user_id = {$uid}")->fetchColumn();
$receivableTotal = (float) $pdo->query("SELECT COALESCE(SUM(GREATEST(total_amount-paid_amount,0)),0) FROM receivables WHERE user_id = {$uid}")->fetchColumn();
$netWorth = $balance + $savingsTotal + $receivableTotal - $debtTotal;
$recentStmt = $pdo->prepare('SELECT * FROM transactions WHERE user_id = ? ORDER BY transaction_date DESC, id DESC LIMIT 7'); $recentStmt->execute([$uid]); $recent = $recentStmt->fetchAll();
$goalStmt = $pdo->prepare('SELECT * FROM financial_goals WHERE user_id = ? AND status = "Aktif" ORDER BY deadline IS NULL, deadline LIMIT 3'); $goalStmt->execute([$uid]); $goals = $goalStmt->fetchAll();
$budgetStmt = $pdo->prepare('SELECT b.*, COALESCE((SELECT SUM(t.amount) FROM transactions t WHERE t.user_id=b.user_id AND t.type="expense" AND t.category=b.category AND t.transaction_date BETWEEN CONCAT(b.year,"-",LPAD(b.month,2,"0"),"-01") AND LAST_DAY(CONCAT(b.year,"-",LPAD(b.month,2,"0"),"-01"))),0) used_amount FROM budgets b WHERE b.user_id=? AND b.month=? AND b.year=? ORDER BY used_amount DESC'); $budgetStmt->execute([$uid,(int)date('m'),(int)date('Y')]); $budgets = $budgetStmt->fetchAll();
$monthlyLabels=[];$monthlyIncome=[];$monthlyExpense=[];$monthlyBalance=[];$running=0;
for($i=5;$i>=0;$i--){$stamp=strtotime("first day of -{$i} month");$label=date('M Y',$stamp);$start=date('Y-m-01',$stamp);$end=date('Y-m-t',$stamp);$monthlyLabels[]=$label;$monthlyIncome[]=transactionSum($pdo,$uid,'income',$start,$end);$monthlyExpense[]=transactionSum($pdo,$uid,'expense',$start,$end);$running += $monthlyIncome[array_key_last($monthlyIncome)]-$monthlyExpense[array_key_last($monthlyExpense)];$monthlyBalance[]=$running;}
$catStmt=$pdo->prepare('SELECT category,SUM(amount) total FROM transactions WHERE user_id=? AND type="expense" AND transaction_date BETWEEN ? AND ? GROUP BY category ORDER BY total DESC LIMIT 7');$catStmt->execute([$uid,$monthStart,$monthEnd]);$catRows=$catStmt->fetchAll();$catLabels=array_column($catRows,'category');$catValues=array_map('floatval',array_column($catRows,'total'));
$insights=[];
if($catRows){$insights[]='Pengeluaran terbesar bulan ini berasal dari kategori <strong>'.e($catRows[0]['category']).'</strong> sebesar '.formatRupiah($catRows[0]['total']).'.';}
[$prevStart,$prevEnd]=monthBounds(date('Y-m',strtotime('-1 month')));$prevExpense=transactionSum($pdo,$uid,'expense',$prevStart,$prevEnd);if($prevExpense>0 && $expenseMonth>$prevExpense){$insights[]='Pengeluaran bulan ini naik '.number_format((($expenseMonth-$prevExpense)/$prevExpense)*100,1,',','.').'% dibanding bulan lalu.';}elseif($prevExpense>0){$insights[]='Pengeluaran bulan ini lebih rendah dibandingkan bulan lalu. Pertahankan ritmenya.';}
foreach($budgets as $budget){$used=(float)$budget['used_amount'];$percent=percentage($used,(float)$budget['amount']);if($percent>=85){$insights[]='Budget kategori <strong>'.e($budget['category']).'</strong> sudah mencapai '.number_format($percent,1,',','.').'%. ';break;}}
foreach($goals as $goal){$percent=percentage((float)$goal['current_amount'],(float)$goal['target_amount']);if($percent>=50){$insights[]='Target <strong>'.e($goal['name']).'</strong> sudah mencapai '.number_format($percent,1,',','.').'%. ';break;}}
$soonStmt=$pdo->prepare('SELECT name,due_date FROM bills WHERE user_id=? AND status="Belum Dibayar" AND due_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(),INTERVAL 3 DAY) LIMIT 1');$soonStmt->execute([$uid]);if($soon=$soonStmt->fetch())$insights[]='Tagihan <strong>'.e($soon['name']).'</strong> jatuh tempo dalam 3 hari.';
if($receivableTotal>0)$insights[]='Masih ada piutang sebesar <strong>'.formatRupiah($receivableTotal).'</strong> yang belum diterima.';
if(!$insights)$insights[]='Belum ada insight khusus. Tambahkan transaksi agar kondisi keuanganmu semakin terbaca.';
$user=currentUser($pdo); require __DIR__.'/includes/header.php';
?>
<div class="page-heading"><div><p class="eyebrow">Rabu, <?= e(date('d F Y')) ?></p><h1>Selamat datang kembali, Bagas</h1><p>Berikut ringkasan kondisi keuanganmu hari ini.</p></div><div class="page-heading-actions"><a class="btn btn-primary" href="pemasukan.php?action=add"><i data-lucide="plus"></i> Catat pemasukan</a><a class="btn btn-ghost" href="pengeluaran.php?action=add"><i data-lucide="arrow-up-right"></i> Catat pengeluaran</a></div></div>
<div class="stats-grid"><div class="stat-card card kpi-highlight"><div class="stat-top"><span>Saldo Saat Ini</span><span class="stat-icon"><i data-lucide="wallet"></i></span></div><div class="stat-value"><?= formatRupiah($balance) ?></div><div class="stat-meta">Pemasukan total dikurangi pengeluaran</div></div><div class="stat-card card"><div class="stat-top"><span>Pemasukan Bulan Ini</span><span class="stat-icon"><i data-lucide="trending-up"></i></span></div><div class="stat-value positive"><?= formatRupiah($incomeMonth) ?></div><div class="stat-meta"><?= e(date('F Y')) ?></div></div><div class="stat-card card"><div class="stat-top"><span>Pengeluaran Bulan Ini</span><span class="stat-icon"><i data-lucide="trending-down"></i></span></div><div class="stat-value negative"><?= formatRupiah($expenseMonth) ?></div><div class="stat-meta"><?= e(date('F Y')) ?></div></div><div class="stat-card card"><div class="stat-top"><span>Sisa Uang Bulan Ini</span><span class="stat-icon"><i data-lucide="sparkles"></i></span></div><div class="stat-value <?= $monthBalance>=0?'positive':'negative' ?>"><?= formatRupiah($monthBalance) ?></div><div class="stat-meta">Arus kas bulan berjalan</div></div></div>
<div class="stats-grid"><div class="stat-card card"><div class="stat-top"><span>Total Tabungan</span><span class="stat-icon"><i data-lucide="piggy-bank"></i></span></div><div class="stat-value"><?= formatRupiah($savingsTotal) ?></div><div class="stat-meta">Alokasi target uang</div></div><div class="stat-card card"><div class="stat-top"><span>Total Utang</span><span class="stat-icon"><i data-lucide="credit-card"></i></span></div><div class="stat-value negative"><?= formatRupiah($debtTotal) ?></div><div class="stat-meta">Sisa yang belum lunas</div></div><div class="stat-card card"><div class="stat-top"><span>Total Piutang</span><span class="stat-icon"><i data-lucide="hand-coins"></i></span></div><div class="stat-value positive"><?= formatRupiah($receivableTotal) ?></div><div class="stat-meta">Sisa yang harus diterima</div></div><div class="stat-card card"><div class="stat-top"><span>Net Worth</span><span class="stat-icon"><i data-lucide="badge-dollar-sign"></i></span></div><div class="stat-value"><?= formatRupiah($netWorth) ?></div><div class="stat-meta">Saldo + tabungan + piutang - utang</div></div></div>
<div class="grid-main"><section class="card"><div class="card-header"><div><h2 class="card-title">Pemasukan vs Pengeluaran</h2><p class="card-subtitle">Tren enam bulan terakhir</p></div><a class="btn btn-soft btn-sm" href="laporan.php">Lihat laporan</a></div><div class="chart-wrap"><canvas id="cashflowChart"></canvas></div></section><section class="card"><div class="card-header"><div><h2 class="card-title">Pengeluaran per Kategori</h2><p class="card-subtitle">Bulan berjalan</p></div></div><div class="chart-wrap small"><canvas id="categoryChart"></canvas></div></section></div>
<div class="grid-two"><section class="card"><div class="card-header"><div><h2 class="card-title">Perkembangan Saldo</h2><p class="card-subtitle">Akumulasi arus kas enam bulan terakhir</p></div></div><div class="chart-wrap small"><canvas id="balanceChart"></canvas></div></section><section class="card"><div class="card-header"><div><h2 class="card-title">Aksi Cepat</h2><p class="card-subtitle">Satu klik untuk menjaga catatan tetap rapi</p></div></div><div class="quick-actions"><a class="quick-action" href="pemasukan.php?action=add"><i><i data-lucide="arrow-down-left"></i></i>Tambah Pemasukan</a><a class="quick-action" href="pengeluaran.php?action=add"><i><i data-lucide="arrow-up-right"></i></i>Tambah Pengeluaran</a><a class="quick-action" href="tabungan.php?action=add"><i><i data-lucide="piggy-bank"></i></i>Tambah Tabungan</a><a class="quick-action" href="utang.php?action=add"><i><i data-lucide="credit-card"></i></i>Tambah Utang</a><a class="quick-action" href="piutang.php?action=add"><i><i data-lucide="hand-coins"></i></i>Tambah Piutang</a><a class="quick-action" href="tagihan.php?action=add"><i><i data-lucide="receipt-text"></i></i>Tambah Tagihan</a></div></section></div>
<div class="grid-two"><section class="card"><div class="card-header"><div><h2 class="card-title">Transaksi Terbaru</h2><p class="card-subtitle">Aktivitas keuangan terakhir</p></div><a class="btn btn-ghost btn-sm" href="pencarian.php">Lihat semua</a></div><?php if(!$recent): ?><div class="empty-state"><div class="empty-icon"><i data-lucide="inbox"></i></div><strong>Belum ada transaksi.</strong><p>Mulai catat pemasukan atau pengeluaran pertamamu.</p><a class="btn btn-primary btn-sm" href="pemasukan.php?action=add">Tambah Transaksi</a></div><?php else: ?><div class="list"><?php foreach($recent as $item): ?><div class="transaction-row"><div class="type-dot <?= e($item['type']) ?>"><i data-lucide="<?= $item['type']==='income'?'arrow-down-left':'arrow-up-right' ?>"></i></div><div class="row-main"><strong><?= e($item['description'] ?: $item['category']) ?></strong><small><?= e($item['category']) ?> · <?= e(date('d/m/Y',strtotime($item['transaction_date']))) ?></small></div><div class="row-amount <?= e($item['type']) ?>"><?= $item['type']==='income'?'+':'-' ?><?= formatRupiah($item['amount']) ?></div></div><?php endforeach; ?></div><?php endif; ?></section><section class="card"><div class="card-header"><div><h2 class="card-title">Insight Keuangan</h2><p class="card-subtitle">Sinyal sederhana dari datamu</p></div><span class="stat-icon"><i data-lucide="lightbulb"></i></span></div><div class="insight-list"><?php foreach($insights as $insight): ?><div class="insight"><div class="insight-icon"><i data-lucide="sparkles"></i></div><span><?= $insight ?></span></div><?php endforeach; ?></div></section></div>
<?php if($budgets): ?><section class="card" style="margin-bottom:18px"><div class="card-header"><div><h2 class="card-title">Progress Budget Bulan Ini</h2><p class="card-subtitle">Tetap dekat dengan rencana pengeluaranmu</p></div><a class="btn btn-ghost btn-sm" href="budget.php">Kelola budget</a></div><div class="grid-two" style="margin:0"><?php foreach($budgets as $budget): [$label,$tone,$percent]=statusBudget((float)$budget['used_amount'],(float)$budget['amount']); ?><div><div class="progress-meta"><span><strong><?= e($budget['category']) ?></strong> · <?= e($label) ?></span><span><?= number_format($percent,1,',','.') ?>%</span></div><div class="progress-line"><div class="progress-fill <?= e($tone) ?>" style="width:<?= $percent ?>%"></div></div><div class="form-hint" style="margin-top:5px"><?= formatRupiah($budget['used_amount']) ?> dari <?= formatRupiah($budget['amount']) ?></div></div><?php endforeach; ?></div></section><?php endif; ?>
<?php $chartData=['labels'=>$monthlyLabels,'income'=>$monthlyIncome,'expense'=>$monthlyExpense,'balance'=>$monthlyBalance,'categoryLabels'=>$catLabels,'categoryValues'=>$catValues];$pageScripts='<script>const dashboardData='.json_encode($chartData,JSON_UNESCAPED_UNICODE).';const gridColor="rgba(123,135,158,.15)";const base={responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{font:{family:"Inter",size:11},usePointStyle:true,boxWidth:8}}},scales:{x:{grid:{display:false},ticks:{color:"#9aa5b8",font:{size:10}}},y:{grid:{color:gridColor},ticks:{color:"#9aa5b8",font:{size:10},callback:v=>"Rp "+new Intl.NumberFormat("id-ID",{notation:"compact"}).format(v)}}}};new Chart(document.getElementById("cashflowChart"),{type:"bar",data:{labels:dashboardData.labels,datasets:[{label:"Pemasukan",data:dashboardData.income,backgroundColor:"#18a999",borderRadius:8},{label:"Pengeluaran",data:dashboardData.expense,backgroundColor:"#ec8b75",borderRadius:8}]},options:base});new Chart(document.getElementById("categoryChart"),{type:"doughnut",data:{labels:dashboardData.categoryLabels.length?dashboardData.categoryLabels:["Belum ada data"],datasets:[{data:dashboardData.categoryValues.length?dashboardData.categoryValues:[1],backgroundColor:["#5b62da","#18a999","#ec8b75","#e9aa43","#8e73dc","#4b9ec7","#a8b1c3"],borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:"bottom",labels:{font:{family:"Inter",size:10},usePointStyle:true,boxWidth:8}}}}});new Chart(document.getElementById("balanceChart"),{type:"line",data:{labels:dashboardData.labels,datasets:[{label:"Saldo",data:dashboardData.balance,borderColor:"#5b62da",backgroundColor:"rgba(91,98,218,.12)",fill:true,tension:.38,pointRadius:3}]},options:base});</script>';require __DIR__.'/includes/footer.php';