<?php
require_once __DIR__.'/includes/auth.php';requireLogin();$pdo=db();$pageTitle='Kalkulator';$activePage='kalkulator.php';$user=currentUser($pdo);require __DIR__.'/includes/header.php';
?>
<div class="page-heading"><div><p class="eyebrow">Bantu ambil keputusan</p><h1>Kalkulator Keuangan</h1><p>Semua hasil dihitung langsung di browser tanpa reload.</p></div></div>
<div class="calc-grid"><section class="card"><div class="card-header"><div><h2 class="card-title">Kalkulator Budget</h2><p class="card-subtitle">Hitung sisa pendapatan setelah pengeluaran.</p></div><span class="stat-icon"><i data-lucide="wallet-cards"></i></span></div><div class="form-grid"><div class="form-field"><label>Pendapatan</label><input class="input calc-input" id="budget-income" inputmode="decimal" value="0"></div><div class="form-field"><label>Pengeluaran</label><input class="input calc-input" id="budget-expense" inputmode="decimal" value="0"></div></div><div class="calc-result">Sisa<strong id="budget-result">Rp 0</strong></div></section>
<section class="card"><div class="card-header"><div><h2 class="card-title">Kalkulator Tabungan</h2><p class="card-subtitle">Lihat nominal yang masih perlu dikumpulkan.</p></div><span class="stat-icon"><i data-lucide="piggy-bank"></i></span></div><div class="form-grid"><div class="form-field"><label>Target</label><input class="input calc-input" id="saving-target" inputmode="decimal" value="0"></div><div class="form-field"><label>Tabungan sekarang</label><input class="input calc-input" id="saving-current" inputmode="decimal" value="0"></div></div><div class="calc-result">Sisa<strong id="saving-result">Rp 0</strong></div></section>
<section class="card"><div class="card-header"><div><h2 class="card-title">Kalkulator Target</h2><p class="card-subtitle">Bagi target berdasarkan sisa bulan.</p></div><span class="stat-icon"><i data-lucide="goal"></i></span></div><div class="form-grid"><div class="form-field"><label>Target</label><input class="input calc-input" id="goal-target" inputmode="decimal" value="0"></div><div class="form-field"><label>Deadline</label><input class="input calc-input" id="goal-deadline" type="date"></div><div class="form-field"><label>Nominal saat ini</label><input class="input calc-input" id="goal-current" inputmode="decimal" value="0"></div></div><div class="calc-result">Kebutuhan per bulan<strong id="goal-result">Rp 0</strong></div></section>
<section class="card"><div class="card-header"><div><h2 class="card-title">Kalkulator Cicilan</h2><p class="card-subtitle">Estimasi cicilan sederhana tanpa bunga.</p></div><span class="stat-icon"><i data-lucide="credit-card"></i></span></div><div class="form-grid"><div class="form-field"><label>Total</label><input class="input calc-input" id="installment-total" inputmode="decimal" value="0"></div><div class="form-field"><label>Tenor (bulan)</label><input class="input calc-input" id="installment-tenor" type="number" min="1" value="1"></div></div><div class="calc-result">Per bulan<strong id="installment-result">Rp 0</strong></div></section>
<section class="card"><div class="card-header"><div><h2 class="card-title">Kalkulator Persentase</h2><p class="card-subtitle">Hitung proporsi nominal dengan cepat.</p></div><span class="stat-icon"><i data-lucide="percent"></i></span></div><div class="form-grid"><div class="form-field"><label>Nominal</label><input class="input calc-input" id="percent-amount" inputmode="decimal" value="0"></div><div class="form-field"><label>Persentase (%)</label><input class="input calc-input" id="percent-value" inputmode="decimal" value="0"></div></div><div class="calc-result">Hasil<strong id="percent-result">Rp 0</strong></div></section></div>
<?php $pageScripts='<script>const n=id=>parseFloat((document.getElementById(id)?.value||"0").replace(/\./g,"").replace(",","."))||0;const rp=v=>"Rp "+new Intl.NumberFormat("id-ID").format(Math.round(v));const calc=()=>{document.getElementById("budget-result").textContent=rp(n("budget-income")-n("budget-expense"));document.getElementById("saving-result").textContent=rp(Math.max(0,n("saving-target")-n("saving-current")));const date=document.getElementById("goal-deadline").value;let months=1;if(date){months=Math.max(1,Math.ceil((new Date(date)-new Date())/(30*86400000)))}document.getElementById("goal-result").textContent=rp(Math.max(0,n("goal-target")-n("goal-current"))/months);document.getElementById("installment-result").textContent=rp(n("installment-total")/Math.max(1,n("installment-tenor")));document.getElementById("percent-result").textContent=rp(n("percent-amount")*n("percent-value")/100)};document.querySelectorAll(".calc-input").forEach(x=>x.addEventListener("input",calc));calc();</script>';require __DIR__.'/includes/footer.php';?>